# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Integration tests for the local Scene Optimizer backend.

Runs the real SO subprocess against the regression test scene and verifies
correspondence maps against the checked-in ground truth (generated by the
NVCF Kit service).

All 8 operation combinations are tested:
- no_op, D_only, S_only, P_only, DS, DP, SP, DSP

These tests require an unpacked Scene Optimizer Core package. Populate it
via ``scripts/fetch_build_resources.sh`` and point ``WU_SO_PACKAGE_DIR`` at
the resulting ``.build-resources/scene_optimizer_core/`` directory.
"""

import json
import os
from pathlib import Path

import pytest

from world_understanding.functions.graphics.scene_optimizer_local import (
    optimize_usd_local,
)

# ---------------------------------------------------------------------------
# Optional dependency check — skip all tests if SO Core is not available
# ---------------------------------------------------------------------------


def _so_core_available() -> bool:
    pkg = os.environ.get("WU_SO_PACKAGE_DIR")
    if not pkg:
        return False
    root = Path(pkg)
    required_subdirs = ("python", "lib", "extraLibs", "usdpy")
    return all((root / sub).is_dir() for sub in required_subdirs)


HAS_SO_CORE = _so_core_available()

pytestmark = pytest.mark.skipif(
    not HAS_SO_CORE,
    reason="scene_optimizer_core not unpacked (set WU_SO_PACKAGE_DIR)",
)

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

_DATA_DIR = (
    Path(__file__).parent.parent
    / "apps"
    / "material_agent"
    / "data"
    / "regression"
    / "scene_optimizer"
)

_TEST_SCENE = _DATA_DIR / "scene_optimizer_test.usda"


@pytest.fixture(scope="module")
def test_scene_path() -> Path:
    """Return the path to the regression test USD scene."""
    assert _TEST_SCENE.exists(), f"Test scene not found: {_TEST_SCENE}"
    return _TEST_SCENE


def _load_ground_truth(combo: str) -> dict:
    """Load ground truth correspondence map for a given operation combo."""
    gt_path = _DATA_DIR / f"correspondence_map_{combo}.json"
    assert gt_path.exists(), f"Ground truth not found: {gt_path}"
    with open(gt_path, encoding="utf-8") as f:
        return json.load(f)


def _get_section_o2p(o2p: dict, section_prefix: str) -> dict:
    """Filter original_to_prototype to entries under a specific section."""
    return {k: v for k, v in o2p.items() if k.startswith(section_prefix)}


# ---------------------------------------------------------------------------
# Integration tests — compare against ground truth
# ---------------------------------------------------------------------------


class TestSceneOptimizerLocalIntegration:
    """Integration tests that run the real Scene Optimizer subprocess."""

    def test_no_op(self, test_scene_path: Path, tmp_path: Path):
        """No operations — all meshes map to themselves (identity)."""
        result = optimize_usd_local(
            input_path=test_scene_path,
            output_path=tmp_path / "output_no_op.usdc",
            optimization_config={
                "scene_optimizer_settings": {
                    "enable_deinstance": False,
                    "enable_split_meshes": False,
                    "enable_deduplicate": False,
                }
            },
        )

        assert result["status"] == "success", result.get("error")

        cm = result["correspondence_map"]
        o2p = cm["full_mapping"]["original_to_prototype"]

        assert cm["split_mapping"] == {}
        assert cm["deduplication_mapping"]["instance_to_prototype"] == {}

        # All entries should be identity
        for orig, prototypes in o2p.items():
            assert prototypes == [orig], (
                f"Expected identity for {orig}, got {prototypes}"
            )

        # Control group entry present
        assert "/World/ControlGroup/SimpleMesh" in o2p

    def test_split_only(self, test_scene_path: Path, tmp_path: Path):
        """splitMeshes only — verify split mapping matches S_only ground truth."""
        result = optimize_usd_local(
            input_path=test_scene_path,
            output_path=tmp_path / "output_split.usdc",
            optimization_config={
                "scene_optimizer_settings": {
                    "enable_deinstance": False,
                    "enable_split_meshes": True,
                    "enable_deduplicate": False,
                }
            },
        )

        assert result["status"] == "success", result.get("error")

        cm = result["correspondence_map"]
        o2p = cm["full_mapping"]["original_to_prototype"]
        gt = _load_ground_truth("S_only")
        gt_o2p = gt["full_mapping"]["original_to_prototype"]

        # Check SplitGeomSubsetsTest section
        section = "/World/SplitGeomSubsetsTest"
        local_section = _get_section_o2p(o2p, section)
        gt_section = _get_section_o2p(gt_o2p, section)

        assert set(local_section.keys()) == set(gt_section.keys()), (
            f"Key mismatch for {section}"
        )
        for prim_path in gt_section:
            assert sorted(local_section[prim_path]) == sorted(gt_section[prim_path]), (
                f"Mapping mismatch for {prim_path}: "
                f"local={local_section[prim_path]}, gt={gt_section[prim_path]}"
            )

        # Check SplitDedupTest arrows are also split
        for arrow in ["ArrowMesh1", "ArrowMesh2", "ArrowMesh3"]:
            key = f"/World/SplitDedupTest/{arrow}"
            assert key in o2p, f"Expected {key} in o2p"
            assert len(o2p[key]) == 2, f"Expected 2 split parts for {key}"

        # ControlGroup should be identity
        assert o2p["/World/ControlGroup/SimpleMesh"] == [
            "/World/ControlGroup/SimpleMesh"
        ]

    def test_dedup_only(self, test_scene_path: Path, tmp_path: Path):
        """deduplicateGeometry only — verify dedup mapping matches P_only GT."""
        result = optimize_usd_local(
            input_path=test_scene_path,
            output_path=tmp_path / "output_dedup.usdc",
            optimization_config={
                "scene_optimizer_settings": {
                    "enable_deinstance": False,
                    "enable_split_meshes": False,
                    "enable_deduplicate": True,
                }
            },
        )

        assert result["status"] == "success", result.get("error")

        cm = result["correspondence_map"]
        o2p = cm["full_mapping"]["original_to_prototype"]
        gt = _load_ground_truth("P_only")
        gt_o2p = gt["full_mapping"]["original_to_prototype"]

        # Check DeduplicationTest section — pyramids should be deduped
        section = "/World/DeduplicationTest"
        local_section = _get_section_o2p(o2p, section)
        gt_section = _get_section_o2p(gt_o2p, section)

        assert set(local_section.keys()) == set(gt_section.keys()), (
            f"Key mismatch for {section}"
        )
        for prim_path in gt_section:
            assert sorted(local_section[prim_path]) == sorted(gt_section[prim_path]), (
                f"Mapping mismatch for {prim_path}: "
                f"local={local_section[prim_path]}, gt={gt_section[prim_path]}"
            )

        # All 3 pyramids should map to the same prototype
        pyramid_targets = set()
        for i in [1, 2, 3]:
            key = f"/World/DeduplicationTest/DuplicatePyramid{i}"
            assert key in o2p
            pyramid_targets.update(o2p[key])
        assert len(pyramid_targets) == 1, (
            f"All pyramids should map to one prototype, got {pyramid_targets}"
        )

        # ControlGroup should be identity
        assert o2p["/World/ControlGroup/SimpleMesh"] == [
            "/World/ControlGroup/SimpleMesh"
        ]

    def test_split_and_dedup(self, test_scene_path: Path, tmp_path: Path):
        """splitMeshes + deduplicateGeometry — verify against SP ground truth."""
        result = optimize_usd_local(
            input_path=test_scene_path,
            output_path=tmp_path / "output_sp.usdc",
            optimization_config={
                "scene_optimizer_settings": {
                    "enable_deinstance": False,
                    "enable_split_meshes": True,
                    "enable_deduplicate": True,
                }
            },
        )

        assert result["status"] == "success", result.get("error")

        cm = result["correspondence_map"]
        o2p = cm["full_mapping"]["original_to_prototype"]
        gt = _load_ground_truth("SP")
        gt_o2p = gt["full_mapping"]["original_to_prototype"]

        # Check SplitDedupTest — arrows split then deduped
        section = "/World/SplitDedupTest"
        local_section = _get_section_o2p(o2p, section)
        gt_section = _get_section_o2p(gt_o2p, section)

        assert set(local_section.keys()) == set(gt_section.keys()), (
            f"Key mismatch for {section}"
        )
        for prim_path in gt_section:
            assert sorted(local_section[prim_path]) == sorted(gt_section[prim_path]), (
                f"Mapping mismatch for {prim_path}: "
                f"local={local_section[prim_path]}, gt={gt_section[prim_path]}"
            )

        # ArrowMesh2 and ArrowMesh3 should share prototypes with ArrowMesh1
        arrow1_protos = sorted(o2p.get("/World/SplitDedupTest/ArrowMesh1", []))
        arrow2_protos = sorted(o2p.get("/World/SplitDedupTest/ArrowMesh2", []))
        arrow3_protos = sorted(o2p.get("/World/SplitDedupTest/ArrowMesh3", []))
        assert arrow1_protos == arrow2_protos == arrow3_protos, (
            f"Arrow prototypes should match: {arrow1_protos} vs {arrow2_protos} vs {arrow3_protos}"
        )

        # DeduplicationTest pyramids should also be deduped
        section_p = "/World/DeduplicationTest"
        local_p = _get_section_o2p(o2p, section_p)
        gt_p = _get_section_o2p(gt_o2p, section_p)
        for prim_path in gt_p:
            assert sorted(local_p[prim_path]) == sorted(gt_p[prim_path]), (
                f"Pyramid mapping mismatch for {prim_path}"
            )

    # ------------------------------------------------------------------
    # Deinstance combos (D_only, DS, DP, DSP)
    # ------------------------------------------------------------------

    def test_deinstance_only(self, test_scene_path: Path, tmp_path: Path):
        """D_only — deinstance, no split/dedup. All prims identity."""
        result = optimize_usd_local(
            input_path=test_scene_path,
            output_path=tmp_path / "output_d.usdc",
            optimization_config={
                "scene_optimizer_settings": {
                    "enable_deinstance": True,
                    "enable_split_meshes": False,
                    "enable_deduplicate": False,
                }
            },
        )

        assert result["status"] == "success", result.get("error")

        cm = result["correspondence_map"]
        o2p = cm["full_mapping"]["original_to_prototype"]
        gt = _load_ground_truth("D_only")
        gt_o2p = gt["full_mapping"]["original_to_prototype"]

        # All sections should match ground truth
        assert set(o2p.keys()) == set(gt_o2p.keys()), "Key mismatch for D_only"
        for prim_path in gt_o2p:
            assert sorted(o2p[prim_path]) == sorted(gt_o2p[prim_path]), (
                f"D_only mismatch for {prim_path}"
            )

    def test_deinstance_split(self, test_scene_path: Path, tmp_path: Path):
        """DS — deinstance + split."""
        result = optimize_usd_local(
            input_path=test_scene_path,
            output_path=tmp_path / "output_ds.usdc",
            optimization_config={
                "scene_optimizer_settings": {
                    "enable_deinstance": True,
                    "enable_split_meshes": True,
                    "enable_deduplicate": False,
                }
            },
        )

        assert result["status"] == "success", result.get("error")

        cm = result["correspondence_map"]
        o2p = cm["full_mapping"]["original_to_prototype"]
        gt = _load_ground_truth("DS")
        gt_o2p = gt["full_mapping"]["original_to_prototype"]

        assert set(o2p.keys()) == set(gt_o2p.keys()), "Key mismatch for DS"
        for prim_path in gt_o2p:
            assert sorted(o2p[prim_path]) == sorted(gt_o2p[prim_path]), (
                f"DS mismatch for {prim_path}"
            )

    def test_deinstance_dedup(self, test_scene_path: Path, tmp_path: Path):
        """DP — deinstance + dedup."""
        result = optimize_usd_local(
            input_path=test_scene_path,
            output_path=tmp_path / "output_dp.usdc",
            optimization_config={
                "scene_optimizer_settings": {
                    "enable_deinstance": True,
                    "enable_split_meshes": False,
                    "enable_deduplicate": True,
                }
            },
        )

        assert result["status"] == "success", result.get("error")

        cm = result["correspondence_map"]
        o2p = cm["full_mapping"]["original_to_prototype"]
        gt = _load_ground_truth("DP")
        gt_o2p = gt["full_mapping"]["original_to_prototype"]

        assert set(o2p.keys()) == set(gt_o2p.keys()), "Key mismatch for DP"
        for prim_path in gt_o2p:
            assert sorted(o2p[prim_path]) == sorted(gt_o2p[prim_path]), (
                f"DP mismatch for {prim_path}"
            )

    def test_deinstance_split_dedup(self, test_scene_path: Path, tmp_path: Path):
        """DSP — all three operations."""
        result = optimize_usd_local(
            input_path=test_scene_path,
            output_path=tmp_path / "output_dsp.usdc",
            optimization_config={
                "scene_optimizer_settings": {
                    "enable_deinstance": True,
                    "enable_split_meshes": True,
                    "enable_deduplicate": True,
                }
            },
        )

        assert result["status"] == "success", result.get("error")

        cm = result["correspondence_map"]
        o2p = cm["full_mapping"]["original_to_prototype"]
        gt = _load_ground_truth("DSP")
        gt_o2p = gt["full_mapping"]["original_to_prototype"]

        assert set(o2p.keys()) == set(gt_o2p.keys()), "Key mismatch for DSP"
        for prim_path in gt_o2p:
            assert sorted(o2p[prim_path]) == sorted(gt_o2p[prim_path]), (
                f"DSP mismatch for {prim_path}"
            )
